### ISSUE TITLE
Install via pipx?

### ISSUE THREAD

**Issue by scribu** [karlicoss/arctee#3]
Hey, I've been reading your blog and want to use this script, but I'm finding it a hassle to get it set up.

[pipx](https://github.com/pipxproject/pipx) allows Python CLI apps to be installed in isolation.

Would you be interested in converting requirements.txt into a setup.py file and publishing arctee on PyPI?

**Comment by karlicoss** [comment]
Hey, could do later, sure! 
But just out of curiosity, what's the hassle? Apart from having to clone it manually, and [installing the dependencies](https://github.com/karlicoss/arctee#dependencies), it's just a single script.
